CREATE SCHEMA IF NOT EXISTS `krampoline` DEFAULT CHARACTER SET utf8mb4;

GRANT ALL ON *.* TO 'root'@'localhost' IDENTIFIED BY 'root' WITH GRANT OPTION;
GRANT ALL ON krampoline.* TO 'root'@'localhost';
FLUSH PRIVILEGES;

USE `krampoline`;

drop table if exists comment cascade;
drop table if exists policy cascade;

create table comment (
    created_date timestamp(6),
    id bigint generated by default as identity,
    modified_date timestamp(6),
    policy_id bigint,
    content varchar(255),
    writer varchar(255),
    primary key (id)
);

create table policy (
    category tinyint check (category between 0 and 3),
    hate_rate integer not null,
    like_rate integer not null,
    created_date timestamp(6),
    modified_date timestamp(6),
    policy_id bigint generated by default as identity,
    contact varchar(255),
    detail varchar(255),
    name varchar(255),
    subject varchar(255),
    target varchar(255),
    title varchar(255),
    primary key (policy_id)
);

insert into policy values(1, "제주특별자치도 도민기자단", "도내에 주소를 두고 있는 누구나/현장취재와 주요 행사 참석 가능한 누구나/SNS를 즐기는 누구나/유튜브 채널을 운영 중인 누구나", "도민기자증 발급/다양한 도정 주요정책 관련 행사 참여 기회 제공/우수 활동자 시상 및 표창 등", "제주특별자치도 대변인 ☎(064)710-2053", "U", "ACTIVITY");
insert into policy values(2, "제주청년등록시스템 도민기자단", "도내에 주소를 두고 있는 누구나/현장취재와 주요 행사 참석 가능한 누구나/SNS를 즐기는 누구나/유튜브 채널을 운영 중인 누구나", "도민기자증 발급/다양한 도정 주요정책 관련 행사 참여 기회 제공/우수 활동자 시상 및 표창 등", "제주특별자치도 대변인 ☎(064)710-2053", "MA", "ACTIVITY");
insert into policy values(3, "제주청년 갭이어 프로그램 도민기자단", "도내에 주소를 두고 있는 누구나/현장취재와 주요 행사 참석 가능한 누구나/SNS를 즐기는 누구나/유튜브 채널을 운영 중인 누구나", "도민기자증 발급/다양한 도정 주요정책 관련 행사 참여 기회 제공/우수 활동자 시상 및 표창 등", "제주특별자치도 대변인 ☎(064)710-2053", "U", "ACTIVITY");
insert into policy values(4, "청년활동 역량강화 지원 도민기자단", "도내에 주소를 두고 있는 누구나/현장취재와 주요 행사 참석 가능한 누구나/SNS를 즐기는 누구나/유튜브 채널을 운영 중인 누구나", "도민기자증 발급/다양한 도정 주요정책 관련 행사 참여 기회 제공/우수 활동자 시상 및 표창 등", "제주특별자치도 대변인 ☎(064)710-2053", "UF", "ACTIVITY");
insert into policy values(5, "청년공동체 활성화 도민기자단", "도내에 주소를 두고 있는 누구나/현장취재와 주요 행사 참석 가능한 누구나/SNS를 즐기는 누구나/유튜브 채널을 운영 중인 누구나", "도민기자증 발급/다양한 도정 주요정책 관련 행사 참여 기회 제공/우수 활동자 시상 및 표창 등", "제주특별자치도 대변인 ☎(064)710-2053", "F", "ACTIVITY");
insert into policy values(6, "제주청년 자율연구 도민기자단", "도내에 주소를 두고 있는 누구나/현장취재와 주요 행사 참석 가능한 누구나/SNS를 즐기는 누구나/유튜브 채널을 운영 중인 누구나", "도민기자증 발급/다양한 도정 주요정책 관련 행사 참여 기회 제공/우수 활동자 시상 및 표창 등", "제주특별자치도 대변인 ☎(064)710-2053", "F", "ACTIVITY");
insert into policy values(7, "청년정책 아이디어 공모전 도민기자단", "도내에 주소를 두고 있는 누구나/현장취재와 주요 행사 참석 가능한 누구나/SNS를 즐기는 누구나/유튜브 채널을 운영 중인 누구나", "도민기자증 발급/다양한 도정 주요정책 관련 행사 참여 기회 제공/우수 활동자 시상 및 표창 등", "제주특별자치도 대변인 ☎(064)710-2053", "R", "ACTIVITY");
insert into policy values(8, "한라-백두 청년지도자 육성 도민기자단", "도내에 주소를 두고 있는 누구나/현장취재와 주요 행사 참석 가능한 누구나/SNS를 즐기는 누구나/유튜브 채널을 운영 중인 누구나", "도민기자증 발급/다양한 도정 주요정책 관련 행사 참여 기회 제공/우수 활동자 시상 및 표창 등", "제주특별자치도 대변인 ☎(064)710-2053", "URWMFA", "ACTIVITY");
insert into policy values(9, "제주청년의 날 도민기자단", "도내에 주소를 두고 있는 누구나/현장취재와 주요 행사 참석 가능한 누구나/SNS를 즐기는 누구나/유튜브 채널을 운영 중인 누구나", "도민기자증 발급/다양한 도정 주요정책 관련 행사 참여 기회 제공/우수 활동자 시상 및 표창 등", "제주특별자치도 대변인 ☎(064)710-2053", "W", "ACTIVITY");
insert into policy values(10, "타 시도 네트워크 교류 도민기자단", "도내에 주소를 두고 있는 누구나/현장취재와 주요 행사 참석 가능한 누구나/SNS를 즐기는 누구나/유튜브 채널을 운영 중인 누구나", "도민기자증 발급/다양한 도정 주요정책 관련 행사 참여 기회 제공/우수 활동자 시상 및 표창 등", "제주특별자치도 대변인 ☎(064)710-2053", "AU", "ACTIVITY");

-- DROP TABLE IF EXISTS `sample_data`;
-- CREATE TABLE `sample_data` (
--     `id` int(11) NOT NULL AUTO_INCREMENT,
--     `detail` varchar(100) NOT NULL,
--     PRIMARY KEY (`id`)
-- ) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- INSERT INTO sample_data (`id`,`detail`) VALUES ('1', 'Hello DKOS!');
